# Generated by Django 2.2.5 on 2021-05-17 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id_theme',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='task.Theme'),
        ),
    ]
