# Generated by Django 2.2.5 on 2021-05-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210517_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.Profile'),
        ),
    ]
