# Generated by Django 2.2.5 on 2021-05-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20210517_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Profile'),
        ),
    ]
