# Generated by Django 2.2.5 on 2021-05-20 11:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210518_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#0000FF', 'blue'), ('#FF0000', 'red'), ('#00FF00', 'green'), ('#FFF700', 'yellow'), ('#FF5500', 'orange'), ('#D500FF', 'purple'), ('#FF00BC', 'pink'), ('#00C4FF', 'sky-blue')], default='#FFFFFF', max_length=18),
        ),
    ]
