# Generated by Django 2.2.5 on 2021-05-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210520_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='color',
            field=models.CharField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#0000FF', 'blue'), ('#FF0000', 'red'), ('#00FF00', 'green'), ('#FFF700', 'yellow'), ('#FF5500', 'orange'), ('#D500FF', 'purple'), ('#FF00BC', 'pink'), ('#00C4FF', 'sky-blue')], max_length=15),
        ),
    ]
