# Generated by Django 2.2.5 on 2021-05-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20210522_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='color',
        ),
    ]
