# Generated by Django 2.2.5 on 2021-06-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_theme_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id_note',
            new_name='id_task',
        ),
    ]
